/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        TutorialOne one = new TutorialOne();
        one.execTutorial();
    }
}
