import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

//    private static final Pattern EMBULK_CORE_OR_STANDARDS_IN_GRADLE = Pattern.compile(
//            "org\\.embulk:embulk-(?:core|standards):([\\d\\.\\+]+)?");
    private static final Pattern EMBULK_CORE_OR_STANDARDS_IN_GRADLE = Pattern.compile(
            "(org\\.embulk:embulk-(?:core|standards):)([\\d\\.\\+]+)?");

    public static void main(String[] args) {
        try {
            System.out.println("try to open "+args[0]);
            String content = new String(Files.readAllBytes(Paths.get(args[0])));
//            System.out.println(content);
            Matcher matcher = EMBULK_CORE_OR_STANDARDS_IN_GRADLE.matcher(content.substring(0));
            if( matcher.find() ) {
                String modifiedData = matcher.replaceAll(matcher.group(1) + "0.8.27");
                System.out.println(modifiedData);
            }

//        } catch ( Throwable ex ){
//            throw(ex);
        } catch ( IOException ex ){
            System.out.println("ex: " + ex);
            System.exit(1);
        }

    }
}
