import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    private static final Pattern EMBULK_CORE_OR_STANDARDS_IN_GRADLE = Pattern.compile(
            "org\\.embulk:embulk-(?:core|standards):([\\d\\.\\+]+)?",Pattern.MULTILINE);

    public static void main(String[] args) {

        if( args.length < 1 ){
            System.out.println("command file");
            System.exit(1);
        }

        try {
            System.out.println("try to open "+args[0]);
            String content = new String(Files.readAllBytes(Paths.get(args[0])));
            System.out.println(content);
            Matcher matcher = EMBULK_CORE_OR_STANDARDS_IN_GRADLE.matcher(content.substring(0));
            System.out.println("result: " + matcher.matches());

//        } catch ( Throwable ex ){
//            throw(ex);
        } catch ( IOException ex ){
            System.out.println("ex: " + ex);
            System.exit(1);
        }

    }
}
