import com.google.inject.Guice;
import com.google.inject.Injector;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Injector injector = Guice.createInjector(new ExtensionModule());
    }
}
